spring:
  application:
    name: query-demo


--- 
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/queryexample
    username: postgres
    password: Wellness36@
    driver-class-name: org.postgresql.Driver
